name       : deadbeef
version    : 0.7.2
release    : 19
source     :
    - git|https://github.com/DeaDBeeF-Player/deadbeef.git : a764d6c86ab4c9901583f9fabb148d44a11480fb
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : multimedia.audio
summary    : DeaDBeeF is an audio player for GNU/Linux.
description: |
    DeaDBeeF (as in 0xDEADBEEF) is an audio player for GNU/Linux, *BSD, OpenSolaris, Mac OS X, and other UNIX-like systems.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dbus-1)
    - pkgconfig(flac)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(imlib2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcddb)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse-simple)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - intltool
    - libmad-devel
    - yasm
setup      : |
    %autogen --disable-cdda --docdir=/usr/share/doc/deadbeef
build      : |
    %make
install    : |
    %make_install
