name       : deadbeef
version    : 0.7.2
release    : 8
source     :
    - http://freefr.dl.sourceforge.net/project/deadbeef/deadbeef-0.7.2.tar.bz2 : 9cb12b9c947f699669cdb674b4112202d56be4f65ccf45d7a39b24786cef8d67
license    : 
    - LGPL-2.1
    - GPL-2
component  : desktop.multimedia
summary    : DeaDBeeF is an audio player for GNU/Linux.
description: |
    DeaDBeeF (as in 0xDEADBEEF) is an audio player for GNU/Linux, *BSD, OpenSolaris, Mac OS X, and other UNIX-like systems.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dbus-1)
    - pkgconfig(flac)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(imlib2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcddb)
    - pkgconfig(libpulse-simple)
    - pkgconfig(libxml-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - pkgconfig(zlib)
    - curl
    - faad-devel
    - intltool
    - libmad-devel
    - yasm
setup      : |
    %configure \
        --disable-cdda \
        --disable-gtk3 \
        --disable-sndfile \
        --docdir=/usr/share/doc/deadbeef
build      : |
    %make
install    : |
    %make_install
