name       : deadbeef
version    : 1.8.2
release    : 31
source     :
    - https://github.com/DeaDBeeF-Player/deadbeef/archive/1.8.2.tar.gz : a0bc5d505d5a491c21ec360689e3b94e0f4c70be4fe4557a4ecdad109f305df3
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : multimedia.audio
summary    : DeaDBeeF is an audio player for GNU/Linux.
description: |
    DeaDBeeF (as in 0xDEADBEEF) is an audio player for GNU/Linux, *BSD, OpenSolaris, Mac OS X, and other UNIX-like systems.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dbus-1)
    - pkgconfig(flac)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(imlib2)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcddb)
    - pkgconfig(libcurl)
    - pkgconfig(libpulse-simple)
    - pkgconfig(opusfile)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - intltool
    - libmad-devel
    - yasm
rundeps    :
    - opus-tools
    - vorbis-tools
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-non-functional-fdk-AAC-conversion.patch
    %autogen --disable-cdda --docdir=/usr/share/doc/deadbeef
build      : |
    %make
install    : |
    %make_install
